// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yqjvhwtoqohtqsygkfzf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlxanZod3RvcW9odHFzeWdrZnpmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyNjI3NDEsImV4cCI6MjA2NjgzODc0MX0.cbIayiyFJWeKVyVOBcGcsdAStULc6okek64MskPPmN4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});